---
# tasks file for powerdns

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - powerdns

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - powerdns

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - powerdns

- name: Create PowerDNS authoritative server default file
  become: yes
  template:
    src: pdns.default.j2
    dest: /etc/default/pdns
    owner: root
    group: root
    mode: 0644
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS authoritative BIND backend configuration file
  become: yes
  template:
    src: bindbackend.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/bindbackend.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS authoritative server configuration file
  become: yes
  template:
    src: pdns.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/pdns.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS authoritative local configuration file
  become: yes
  template:
    src: pdns.local.conf.j2
    dest: "{{ powerdns_authoritative_include_dir }}/pdns.local.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS authoritative simplebind configuration file
  become: yes
  template:
    src: pdns.simplebind.conf.j2
    dest: "{{ powerdns_authoritative_include_dir }}/pdns.simplebind.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS Mysql backend configuration file
  become: yes
  template:
    src: gmysqlbackend.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/gmysqlbackend.conf"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative and 'gmysql' in powerdns_authoritative_launch
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS ODBC backend configuration file
  become: yes
  template:
    src: godbcbackend.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/godbcbackend.conf"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative and 'godbc' in powerdns_authoritative_launch
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS Oracle backend configuration file
  become: yes
  template:
    src: goraclebackend.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/goraclebackend.conf"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative and 'goracle' in powerdns_authoritative_launch
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS PostgreSQL backend configuration file
  become: yes
  template:
    src: gpgsqlbackend.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/gpgsqlbackend.conf"
    owner: root
    group: root
    mode: 0640
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative and 'gpgsql' in powerdns_authoritative_launch
  tags:
    - powerdns
    - authoritative

- name: Create PowerDNS recursor configuration file
  become: yes
  template:
    src: recursor.conf.j2
    dest: "{{ powerdns_recursor_config_dir }}/recursor.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart powerdns recursor
  when: powerdns_recursor
  tags:
    - powerdns
    - recursor

- name: Ensure PowerDNS authoritative service is started and enabled on boot
  become: yes
  service:
    name: "{{ powerdns_authoritative_service_name }}"
    state: started
    enabled: yes
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Ensure PowerDNS recursor service is started and enabled on boot
  become: yes
  service:
    name: "{{ powerdns_recursor_service_name }}"
    state: started
    enabled: yes
  when: powerdns_recursor
  tags:
    - powerdns
    - recursor
